# Generated by Django 4.2.6 on 2023-11-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
