# Generated by Django 4.2.6 on 2023-11-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_adultcostume_childcostume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AdultCostume',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='Profile',
            field=models.ImageField(blank=True, null=True, upload_to='Profile/'),
        ),
        migrations.RenameModel(
            old_name='ChildCostume',
            new_name='Costume',
        ),
        migrations.AddField(
            model_name='review',
            name='costume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.costume'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customeruser'),
        ),
    ]
