# Generated by Django 4.2.6 on 2023-11-30 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_review_delete_adultcostume_customeruser_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5)]),
        ),
    ]
