# Generated by Django 4.2.6 on 2023-11-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.costume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customeruser')),
            ],
        ),
    ]
