# Generated by Django 4.2.6 on 2023-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_customeruser_groups_customeruser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
