# Generated by Django 4.2.6 on 2023-11-30 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_customeruser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
