# Generated by Django 4.2.6 on 2023-12-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_customeruser_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='some_default_value', max_length=128),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='username',
            field=models.CharField(default='default_username', max_length=255),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='username',
            field=models.CharField(default='default_username', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
