# Generated by Django 4.2.6 on 2023-12-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_rename_profile_customeruser_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
