# Generated by Django 4.2.6 on 2023-12-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_rename_profile_customeruser_profile_adminuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='profile',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='user_permissions',
        ),
    ]
