# Generated by Django 4.2.6 on 2023-12-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_customeruser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
