# Generated by Django 4.2.6 on 2023-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_customeruser_is_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUser',
            new_name='Admin',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
