# Generated by Django 4.2.6 on 2023-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_delete_admin_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('birthdate', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
