# Generated by Django 4.2.6 on 2023-12-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
