# Generated by Django 4.2.6 on 2023-12-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_alter_customeruser_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='Profile',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='status',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff'), ('superuser', 'Superuser')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
