# Generated by Django 4.2.6 on 2023-12-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_remove_customeruser_profile_customeruser_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
