# Generated by Django 4.2.6 on 2023-12-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_alter_customeruser_groups_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
