# Generated by Django 4.2.6 on 2023-12-05 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0040_alter_customeruser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='status',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customeruser_set', related_query_name='user_customer', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customeruser_set', related_query_name='user_customer', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
