# Generated by Django 5.0 on 2024-01-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_chat_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
